Contact
csbasic/curve pull request #5
Opened 2024-05-09 11:09 UTC by csbasic

2024-05-09 18:04 UTC, CollinsTatang requested changes
Hi @csbasic, 

Good job so far!
There are some issues that you still need to work on to go to the next step but you are almost there!

### **Highlights 🚀  ✔️ ✔️ ** 

- The repo looks professional. ✔️ 
- Git/GitHub flow best practices have been followed ✔️ 

## Required changes 
It's ok to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality and help you get a better job.

- [ ] Please update your pull request description. Check the image below
<img width="918" alt="Screenshot 2024-05-09 at 18 57 25" src="https://github.com/csbasic/curve/assets/55596970/507851ee-e3e2-4bd5-8a78-baba5a34edba">

- [x] Please your commit message should be written in the imperative tense. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8). Kindly correct that in your next commit massage.

_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2024-05-09 18:04 UTC, CollinsTatang commented on app/Models/Contact.php
> +    ];
- [x] Kindly add the other contact attribute.

2024-05-09 18:04 UTC, CollinsTatang commented on resources/views/components/layout.blade.php
> +                        // dd($profilePic);
- [x] Please remove all commented code from your codebase.

2024-05-10 16:51 UTC, csbasic commented on resources/views/components/layout.blade.php
> +                        // dd($profilePic);
Comments removed

2024-05-10 16:52 UTC, csbasic commented on app/Models/Contact.php
> +    ];
The rest of contact fillable added

2024-05-10 17:19 UTC, csbasic commented
Instructions given are met.

2024-05-10 19:42 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional. :heavy_check_mark:
- Git/GitHub flow best practices have been followed :heavy_check_mark:
- You have descriptive PR :heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2024-05-10 20:15 UTC, merged